- hosts: centralservers
  become: yes
  roles:
    - crpg-web-ui
    #- nginx
    #- postgresql
    # - datadog
    #- geoip
    #- dotnet
    - crpg-web-api
# - hosts: gameservers
#   become: yes
#   roles:
#     - datadog
#     - crpg-game-server
