---
ansible_connection: ssh
ansible_user: ansible

datadog_dotnet_tracer_version: 2.10.0

steam_api_key: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  62653332643031373433396339646165393539393238613531663166343534616230313134346531
  3530636365323866343666636235363531343838343732630a393236303836656330376432646238
  35323633313835376635616262343433333936393362653861353266653638366363376366353133
  3439363663653831620a646566333061333631363935373738313333346232653830336366653862
  30646138613934646132626664313965306332333362333663616632643630386533633162323131
  3138323137393966623261643162303863336530306637356430

epic_games_client_id: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  30303066323662323262393435653934636532366337653266373538366565653761316165303131
  3332383961383866316263646133393337623765366461310a653433656664313035323364323433
  34663430343566363234303562343031333766363634616437323132616138376431326534656233
  3838323562336361390a666530353533363333653364356261383664303438623739373438613134
  62336232323537336462613630653938353832383464633438663632636239386339366366373731
  3631373334386562363562653937346438313233623261633231

epic_games_client_secret: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  30633266323035383864653436643932396433663739313636613531313732623064643462636161
  6330386538663935316566343730343130663662396130610a643363666138316337356164303234
  64343039343232346562363162653934626562376631316563613565396163356264356636313663
  6236383639633361380a373535306563326538643638376463363630323930326235643837373165
  35303537386133376264663038626164373164373666383866633332333163643835373734306532
  6333353234666531373062623732323437393337633037303435

crpg_game_server_api_secret: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  32326433613332653435346566636265643466643030643234383735333663383433663836656334
  6263343930313465663436303339343262633130653864340a306439393363616435613732323437
  31643762313537653230353636346363383430393765653933303665336339616264316138663038
  3435316531373164640a616437393663666161653465303461306334623362343034386637356162
  62353136616336613035623733333161333235366361643733336534343564643065

crpg_api_domain_name: api.c-rpg.eu
