---
ansible_connection: ssh
ansible_user: ansible

datadog_dotnet_tracer_version: 2.10.0

steam_api_key: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  32653964343863303966333938346363373464653262663864383834636538303738666166633362
  6531633363343230306430313132616232323232303666320a303131323731656637323134643131
  30643034333230393538383963626266353662633834396565636466663539353536656165353335
  3161343935306134640a326339633234623261323135373265636234663830623032356439303939
  65353433656262623061336166343666333530653535333936323533303331663539656630633831
  3238323561636361316235616334326562366264303730376330

epic_games_client_id: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  61353865653665623739633563633933626564623130343662643336363134343166313135663863
  6565313738343862346631353435373432313062646330350a343836326233353239663739336331
  34393762366338333333343635316562633162653932663138306432376431643363323762633430
  6465316635666365610a336564363433646161363632646665363236383936636134613164323462
  6434
epic_games_client_secret: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  61353865653665623739633563633933626564623130343662643336363134343166313135663863
  6565313738343862346631353435373432313062646330350a343836326233353239663739336331
  34393762366338333333343635316562633162653932663138306432376431643363323762633430
  6465316635666365610a336564363433646161363632646665363236383936636134613164323462
  6434
microsoft_client_secret: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  61353865653665623739633563633933626564623130343662643336363134343166313135663863
  6565313738343862346631353435373432313062646330350a343836326233353239663739336331
  34393762366338333333343635316562633162653932663138306432376431643363323762633430
  6465316635666365610a336564363433646161363632646665363236383936636134613164323462
  6434
crpg_game_server_api_secret: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  37326237663864613932666364383863373430303930353934326662313034306137306432303531
  3830373066613633333165356230626163613233383937300a613736646331303631333536643163
  37363938643363346530346166653733396264313036343238636536653837646564326132353936
  3836613332616234360a383330306238386639653539333732663439353438306437643636313539
  63383937363866363633653933623336613564616339303832303637633065393233

crpg_api_domain_name: api.namidaka.fr
