---
ansible_connection: ssh
ansible_user: ansible

ansible_sudo_pass: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  66323536646461616430383436323736313532653037363330346537336431666432366361653438
  3332333437643932353834383338336363616635306362610a623032656162623466653239613437
  39393333333334613531333930336562323637643135303338363365653837643634366131646163
  6464396461366162300a383766366539633839393539346439653662313334363565333731353236
  32393961366339366233393731383165373039346638313661323864353130363835

datadog_api_key: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  63336331303239353839636366306365663262326338343831616564396133386631616539386636
  6436303036373834386662363836623266336536376365330a653532333535666436353230623332
  34386236323063306233383730343034333632643532396532353962653335393863653139653336
  3730653536623865660a356565313035373337313030613966646164623736623937626464373966
  66663735636134326334333164343430616634623761326163316434306530363833626236633430
  6537393033613533636438646634643235666337383030336130
datadog_dotnet_tracer_version: 2.10.0

steam_api_key: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  36343735663636396165643733343038333161646661316635366634313533356135336533646564
  3735393462396232626465313435656464323634623862660a636662393031663765303462323664
  33386162613463386463663561346137623230323330346261366130306466323462363939383234
  6566306239313332640a323437306366336466356230373132626663323337313866666366616232
  64393632396438306233373865346632356564656363336636613161613036383230333037373065
  6132363630623162326566653830653137383266653664366461

crpg_api_keys:
  - 4So4WREgKXKQCN0X4li7XmZxQ6yVJmSqSdJTLc8DLBg= # 01
  - sQfJPbFqc7sXihs6R4twVNmtn7FUEdasiCNO1Ap1MOA= # 02
  - DAAy6362Ch9tnuq3P5AiUSV+odzWCSzFnHHMzsvHC9Y= # 03
  - W7J36L5yioRb7MOqTtb2NCu12lIr/DyHdWohRBLohyY= # 04
  - cn8E7MsclHNqGpXZmqbMiM/j9prtk+shIdCGn2y4xn4= # takeo
  - H7Alh1BMJgHk8U691/UySEvfouF01qpDZs3GZ89SWX4= # Gotha
  - d4OUu1cSQwHmKSgSVVkmGBXlwm+58oXAO/4ZfoszWvc= # Namidaka
  - hwa6o3Ye6aGgi8UQqsLogiVVvsRWbXZ8QIBKcVL45ak= # Demochi
  - R853Vi3Gs1eEkfp+aTyUMEfHHD0HNUi7BKVSWHMZ3P0= # Lubu

patreon_access_token: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  36643932326435323330396133353438316237333637663331343461396161383633356235353335
  3336366463613462343330373034366265353432333234630a616561656638643461663536393139
  32366139666531663862386365313963366631333438613238303133353034393665373162613161
  3335376666643930610a663436373866366163306362653330366134316137623738623339323161
  37633035353338656165636537363438343739656439396561336138356334353938363137306634
  3832656339653031653636623337356532616464366433383839
