name: WebApi

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.100' # SDK Version
    - name: Build
      run: dotnet build --configuration Release src/WebApi
    # Call test on each project individually so the windows-only launcher is not restored.
    - name: Test Application
      run: dotnet test test/Application.UTest
    - name: Test Common
      run: dotnet test test/Common.UTest
    - name: Test Persistence
      run: dotnet test test/Persistence.UTest
    - name: Test Sdk
      run: dotnet test test/Sdk.UTest
