name: WebUI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      dir: ./src/WebUI

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '18.x'
    - name: Install
      run: npm install
      working-directory: ${{env.dir}}
    # - name: Lint
    #   run: npm run lint
    #   working-directory: ${{env.dir}}
    # - name: Unit
    #   run: npm run test:unit
    #   working-directory: ${{env.dir}}
    - name: Build
      run: npm run build
      working-directory: ${{env.dir}}
